import Navigation from '../components/Navigation'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'UNCP - Accesibilidad',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <head>
        <title>
          {metadata.title}
        </title>
      </head>
      <body className={`${inter.className}`+' w-full'} >
        <Navigation/>
        <main className='flex flex-col w-full items-center'>
          <section className='max-w-6xl w-full'>
            {children}
          </section>
        </main>
      </body>
    </html>
  )
}
